version: '3.8'
services:
  user_service:
    build: ./user_service
    volumes:
      - ./user_service:/app
    ports:
      - "5001:5000"
    environment:
      FLASK_APP: "app"
      FLASK_ENV: development
      DATABASE_URL: postgresql://user:password@db/mydatabase
    command: flask run --host=0.0.0.0

  object_service:
    build: ./object_service
    volumes:
      - ./object_service:/app
    ports:
      - "5002:5000"
    environment:
      FLASK_APP: "app"
      FLASK_ENV: development
      DATABASE_URL: postgresql://user:password@db/mydatabase
    command: flask run --host=0.0.0.0

  demand_service:
    build: ./demand_service
    volumes:
      - ./demand_service:/app
    ports:
      - "5003:5000"
    environment:
      FLASK_APP: "app"
      FLASK_ENV: development
      DATABASE_URL: postgresql://user:password@db/mydatabase
    command: flask run --host=0.0.0.0

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: