version: '3.8'
services:
  api_gateway:
    build: ./api_gateway
    volumes:
      - ./api_gateway:/app
    ports:
      - "8000:8000"
    depends_on:
      - user_service
      - object_service
      - demand_service
      - camunda
    environment:
      - GATEWAY_PORT=8000
      - USER_SERVICE_URL=http://user_service:5000
      - OBJECT_SERVICE_URL=http://object_service:5000
      - DEMAND_SERVICE_URL=http://demand_service:5000
      - CAMUNDA_URL=http://camunda:8080
    env_file:
      - .env

  user_service:
    build: ./user_service
    volumes:
      - ./user_service:/app
    ports:
      - "5001:5000"
    environment:
      DATABASE_URL: postgresql://user:password@db/mydatabase
    command: python app/app.py
    depends_on:
      - db

  object_service:
    build: ./object_service
    volumes:
      - ./object_service:/app
    ports:
      - "5002:5000"
    environment:
      DATABASE_URL: postgresql://user:password@db/mydatabase
    command: python app/app.py
    depends_on:
      - db

  demand_service:
    build: ./demand_service
    volumes:
      - ./demand_service:/app
    ports:
      - "5003:5000"
    environment:
      DATABASE_URL: postgresql://user:password@db/mydatabase
      CAMUNDA_URL: http://camunda:8080
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      PYTHONPATH: /app
    command: python -m app.app
    depends_on:
      - db
      - camunda
      - kafka

  camunda:
    image: camunda/camunda-bpm-platform:run-latest
    ports:
      - "8080:8080"
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://db:5432/mydatabase
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - WAIT_FOR=db:5432
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

volumes:
  pgdata: