"""empty message

Revision ID: f2ac6da94ee5
Revises: 
Create Date: 2025-03-25 17:55:49.445050

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'f2ac6da94ee5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('galactic_object_types',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('users',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('permissions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('certificates',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner', postgresql.UUID(), nullable=True),
    sa.Column('valid_from', sa.TIMESTAMP(), nullable=True),
    sa.Column('valid_until', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('galactic_objects',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type_id', postgresql.UUID(), nullable=True),
    sa.Column('mass_kg', sa.Float(), nullable=False),
    sa.Column('radius_km', sa.Float(), nullable=False),
    sa.Column('distance_from_earth_parsec', sa.Float(), nullable=False),
    sa.Column('discovered_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('owner_id', postgresql.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.uuid'], ),
    sa.ForeignKeyConstraint(['type_id'], ['galactic_object_types.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('demands',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('user_id', postgresql.UUID(), nullable=True),
    sa.Column('galactic_object_id', postgresql.UUID(), nullable=True),
    sa.Column('price_eur', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='demand_status'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['galactic_object_id'], ['galactic_objects.uuid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demands')
    op.drop_table('galactic_objects')
    op.drop_table('certificates')
    op.drop_table('users')
    op.drop_table('galactic_object_types')
    # ### end Alembic commands ###
